skpp_general = {
    "->": "to",
    "<-": "from",
    "dmg": "damage",
    "prep": "prepare",
    "?c": "chance",
    "!": "set",
    "rep": "repair",
    "$": "cost",
    "out": "send",
    "pl": "player",
    "end": "stop",
    "?": "if",
    "+=": "add",
    "-=": "remove",
    "==": "is",
    "!=": "is not",
}

skpp_events = {
    "event.cancel()": "cancel event",
    "event.time": "at",
    "event.*": "on",
    "event.anvil_dmg->": "on anvil damage:",
    "event.anvil_prep->": "on anvil prepare:",
    "event.aoe->": "on area cloud effect:",
    "event.arm_swing->": "on arm swing:",
    "event.armor_change->": "on armor change:",
    "event.bed_enter->": "on bed enter:",
    "event.bed_leave->": "on bed leave:",
    "event.bell_res->": "on bell resonate:",
    "event.bell_rng->": "on bell ring:",
    "event.block_dmg->": "on block damage:",
    "event.block_fertilize->": "on block fertilize:",
    "event.crop_grow->": "on crop grow:",
    "event.book_edit->": "on book edit:",
    "event.book_sign->": "on book sign:",
    "event.block_break->": "on block break:",
    "event.block_break": "on break of",
    "event.bucket_empty->": "on bucket empty:",
    "event.bucket_fill->": "on bucket fill:",
    "event.burn->": "on burn:",
    "event.burn": "on burn of",
    "event.build_check->": "on block can build check:",
    "event.chat->": "on chat:",
    "event.chunk_generate->": "on chunk generate:",
    "event.chunk_load->": "on chunk load:",
    "event.chunk_unload->": "on chunk unload:",
    "event.click->": "on click:",
    "event.right_click->": "on rightclick:",
    "event.left_click->": "on leftclick:",
    "event.click": "on click",
# Syntax is slightly unordinary for the click events, the 'event.left_click', etc with no '->' dont include a connecting word like of/on/with, etc, you need to use these events like this: 'event.right_click with diamond' for example
    "event.right_click": "on rightclick",
    "event.left_click": "on leftclick",
    "event.combust->": "on combust:",
    "event.command->": "on command:",
    "event.command": "on command",
    "event.connect->": "on connect:",
    "event.consume->": "on consume:",
    "event.craft->": "on craft:",
    "event.creeper_power->": "on creeper power:",
    "event.dmg->": "on damage:",
    "event.dmg": "on damage of",
    "event.death->": "on death:",
    "event.death": "on death of",
    "event.dispense->": "on dispense:",
    "event.dispense": "on dispense of",
    "event.player_drop->": "on player drop:",
    "event.player_drop": "on player drop of",
    "event.entity_drop->": "on entity drop:",
    "event.entity_drop": "on entity drop of",
    "event.player_egg_throw->": "on player egg throw:",
    "event.egg_throw->": "on egg throw:",
    "event.enchant->": "on enchant:",
    "event.enchant_prep->": "on enchant prepare:",
    "event.enderman_place->": "on enderman place:",
    "event.enderman_pickup->": "on enderman pickup:",
    "event.sheep_eat->": "on sheep eat:",
    "event.silverfish_enter->": "on silverfish enter:",
    "event.silverfish_exit->": "on silverfish exit:",
    "event.falling_block_fall->": "on falling block fall:",
    "event.falling_block_land->": "on falling block land:",
    "event.dismount->": "on dismount:",
    "event.entity_jump->": "on entity jump:",
    "event.mount->": "on mount:",
    "event.entity_portal->": "on entity portal:",
    "event.lvl_change->": "on level progress change:",
    "event.lvl_increase->": "on level progress increase:",
    "event.lvl_decrease->": "on level progress decrease:",
    "event.xp_spawn->": "on xp spawn:",
    "event.explode->": "on explode:",
    "event.explosion_prime->": "on explosion prime:",
    "event.block_fade->": "on block fade:",
    "event.block_fade": "on block fade of",
    "event.firework_explode->": "on firework explode:",
    "event.firework_explode": "on firework explode colored",
    "event.first_join->": "on first join:",
    "event.fish->": "on fish:",
    "event.flight_toggle->": "on flight toggle:",
    "event.block_flow->": "on block flow:",
    "event.form->": "on form:",
    "event.fuel_burn->": "on fuel burn:",
    "event.gamemode_change->": "on gamemode change:",
    "event.gamemode_change": "on gamemode change to",
    "event.glide_toggle->": "on toggle gliding:",
    "event.grow->": "on grow:",
# Same as click events, slightly unordinary syntax for the grow event
    "event.grow": "on grow",
    "event.hand_item_swap->": "on swap hand items:",
    "event.heal->": "on heal:",
    "event.horse_jump->": "on horse jump:",
    "event.hunger_meter_change->": "on hunger meter change:",
    "event.ignite->": "on block ignite:",
    "event.inv_click->": "on inventory click:",
    "event.inv_close->": "on inventory close:",
    "event.inv_drag->": "on inventory drag:",
    "event.inv_item_move->": "on inventory item move:",
    "event.inv_open->": "on inventory open:",
    "event.inv_pickup->": "on inventory pickup:",
    "event.inv_slot_change->": "on inventory slot change:",
    "event.item_break->": "on tool break:",
    "event.item_dmg->": "on item damage:",
    "event.item_despawn->": "on item despawn:",
    "event.item_mend->": "on item mend:",
    "event.item_merge->": "on item merge:",
    "event.item_merge": "on item merge of",
    "event.item_spawn->": "on item spawn:",
    "event.item_spawn": "on item spawn of",
    "event.join->": "on join:",
    "event.jump->": "on jump:",
    "event.kick->": "on kick:",
    "event.lang_change->": "on language change:",
    "event.leaves_decay->": "on leaves decay:",
    "event.lightning->": "on lightning:",
    "event.loot_gen->": "on loot generate:",
    "event.move->": "on move:",
    "event.move_player->": "on player move:",
    "event.step": "on step on",
    "event.physics->": "on block physics:",
    "event.pickup->": "on pick up:",
    "event.pickup": "on pick up of",
    "event.pig_zap->": "on pig zap:",
    "event.piston_extend->": "on piston extend:",
    "event.piston_retract->": "on piston retract:",
    "event.place->": "on place:",
    "event.place": "on place of",
    "event.chunk_enter->": "on player enters a chunk:",
    "event.deep_sleep->": "on player deep sleep:",
    "event.arrow_pickup->": "on arrow pickup:",
    "event.trade->": "on player trade:",
    "event.world_change->": "on world change:",
    "event.portal->": "on player portal:",
    "event.portal_create->": "on portal create:",
    "event.prepare_craft->": "on preparing craft:",
    "event.prepare_craft": "on preparing craft of",
    "event.step_pressure_plate->": "on step on pressure plate:",
    "event.step_tripwire->": "on step on tripewire hook:",
    "event.projectile_collide->": "on projectile collide:",
    "event.projectile_hit->": "on projectile hit:",
    "event.leave->": "on quit:",
    "event.ready_arrow->": "on ready arrow:",
    "event.redstone->": "on redstone change:",
    "event.region_exit->": "on region exit:",
    "event.region_enter->": "on region enter:",
    "event.rsc_pack_response->": "on resource pack request response:",
    "event.rsc_pack_deny->": "on resource pack deny:",
    "event.respawn->": "on respawn:",
    "event.resurrect_attempt->": "on resurrect attempt:",
    "event.riptide->": "on riptide:",
    "event.skpp_load->": "on load:",
    "event.skpp_unload->": "on unload:",
    "event.cmd_list->": "on send command list:",
    "event.srv_list_ping->": "on server list ping:",
    "event.srv_start->": "on server start:",
    "event.srv_stop->": "on server stop:",
    "event.sheep_wool->": "on sheep grow wool:",
    "event.shoot->": "on shoot:",
    "event.sign_change->": "on sign change:",
    "event.slime_split->": "on slime split:",
    "event.smelt->": "on smelt:",
    "event.sneak_toggle->": "on sneak toggle:",
    "event.spawn": "on spawn of",
    "event.spawn_change->": "on spawn change:",
    "event.spectate": "on player start spectating of a",
    "event.sponge_absorb->": "on sponge absorb:",
    "event.spread->": "on spread:",
    "event.sprint_toggle->": "on sprint toggle:",
    "event.stonecut->": "on stonecutting:",
    "event.stop_use_item->": "on stop using item:",
    "event.swim_toggle->": "on swim toggle:",
    "event.tame->": "on tame:",
    "event.target->": "on entity target:",
    "event.tp->": "on teleport:",
    "event.egg_throw->": "on throw of an egg:",
    "event.tool_change->": "on player's held item change:",
    "event.vehicle_block_collide->": "on vehicle block collide:",
    "event.vehicle_entity_collide->": "on vehicle entity collide:",
    "event.vehicle_create->": "on vehicle create:",
    "event.vehicle_dmg->": "on vehicle damage:",
    "event.vehicle_destroy->": "on vehicle destroy:",
    "event.vehicle_enter->": "on vehicle enter:",
    "event.vehicle_exit->": "on vehicle exit:",
    "event.weather->": "on weather change:",
    "event.weather": "on weather change to",
    "event.world_init->": "on world init:",
    "event.world_init": "on world init of",
    "event.world_load->": "on world load:",
    "event.world_load": "on world load of",
    "event.world_save->": "on world save:",
    "event.world_save": "on world save of",
    "event.world_unload->": "on world unload:",
    "event.world_unload": "on world unload of",
    "event.zombie_break_door->": "on zombie break door:",
    "event.periodical": "every"
}

skpp_conditions = {
    "alphanumeric": "",
    "": "",
}